### ISSUE TITLE
Grupo1-DefinirDER

### ISSUE THREAD

**Issue by EzequielMonforte** [ITSC-Practica-Profesionalizante-1-2020/SharedModels#3]
Crear DER con los modelos de bd a utilizar por el equipo

**Comment by JuanPabloPedraza** [comment]
![DiagrabaBDServiceStream](https://user-images.githubusercontent.com/51345057/89964250-0dfd7500-dc20-11ea-8f1a-c2db94c76e54.jpg)
Adjunto el diagrama de base de datos de StreamingService.

**Comment by JuanPabloPedraza** [comment]
close

**Comment by JuanPabloPedraza** [comment]
close #3
